name: Clean ACR Images

on:
  push:
    branches:
      - main  
  workflow_dispatch: # Allows manual triggering

jobs:
  clean-acr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      - name: Azure login
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_APP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: List repositories in ACR
        run: |
          acr_name="your-acr-name" # Replace with your ACR name
          repositories=$(az acr repository list --name $acr_name --output tsv)
          echo "Repositories in ACR: $repositories"
        
      - name: Clean images in Nginx and Redis repositories
        run: |
          acr_name="your-acr-name" # Replace with your ACR name
          
          # Function to delete images except the first 3
          delete_images () {
            repo_name=$1
            images=$(az acr repository show-tags --name $acr_name --repository $repo_name --output tsv | sort -r)
            # Keep the first 3 images
            images_to_delete=$(echo "$images" | tail -n +4)  # Skips the first 3 images
            for image in $images_to_delete; do
              echo "Deleting image: $image from $repo_name"
              az acr repository delete --name $acr_name --repository $repo_name --tag $image --yes
            done
          }

          # Clean images for Nginx and Redis repositories
          delete_images "nginx"
          delete_images "redis"
