name: Purge Old Container Images from ACR

on:
  push:
    branches:
      - main  
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  purge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Login to Azure (Service Principal)
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Get Resource Group Name dynamically
        id: getresourcegroup
        run: |
          # Get the resource group dynamically (optional: use filters if needed)
          resourceGroup=$(az group list --query "[0].name" -o tsv)
          echo "Resource Group: $resourceGroup"
          echo "::set-output name=resourceGroup::$resourceGroup"

      - name: Get ACR name dynamically
        id: getacrname
        run: |
          # Get the ACR name using the dynamically fetched resource group
          acrName=$(az acr list --resource-group ${{ steps.getresourcegroup.outputs.resourceGroup }} --query "[0].name" -o tsv)
          echo "ACR Name: $acrName"
          echo "::set-output name=acrName::$acrName"

      - name: Login to Azure Container Registry
        run: |
          az acr login --name ${{ steps.getacrname.outputs.acrName }}

      - name: Get all repositories in ACR
        id: get_repos
        run: |
          repos=$(az acr repository list --name ${{ steps.getacrname.outputs.acrName }} --output tsv)
          echo "Repositories found: $repos"
          echo "::set-output name=repos::$repos"

      - name: Purge old images from all ACR repositories
        run: |
          for repo in ${{ steps.get_repos.outputs.repos }}; do
            echo "Purging old images in repository: $repo"
            az acr run --registry ${{ steps.getacrname.outputs.acrName }} --cmd "acr purge --filter '$repo:.*' --ago 0d --keep 3 --untagged" /dev/null
          done
