name: Clean up ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_APP_ID }} -p ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: List repositories in ACR
        run: |
          az acr repository list --name ${{ secrets.AZURE_ACR_NAME }} --output tsv > acr_repositories.txt

      - name: List and clean up images in each repository
        run: |
          while read repository; do
            echo "Cleaning up repository: $repository"
            az acr repository show-tags --name ${{ secrets.AZURE_ACR_NAME }} --repository $repository --orderby time_desc --output tsv > acr_tags.txt
            
            if [ -s acr_tags.txt ]; then
              # Keep the first 3 images (most recent)
              tags_to_keep=$(head -n 3 acr_tags.txt)
              
              # Get the list of tags to delete
              tags_to_delete=$(tail -n +4 acr_tags.txt)
              
              for tag in $tags_to_delete; do
                echo "Deleting image with tag $tag from repository $repository"
                az acr repository delete --name ${{ secrets.AZURE_ACR_NAME }} --image "$repository:$tag" --yes --manifest false
              done
            else
              echo "No tags found for repository $repository"
            fi
          done < acr_repositories.txt
