name: Purge Old Container Images from ACR

on:
    workflow_dispatch:

permissions:
    contents: read
    id-token: write
    pull-requests: write

jobs:
    purge:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Azure login
              uses: azure/login@v2
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Get ACR name
              id: getacrname
              run: |
                  acrName=$(az acr list --resource-group ${{ secrets.AZURE_RG_NAME_DEV }} --query "[0].name" -o tsv)
                  echo "::set-output name=acrName::$acrName"    

            - name: Login to Azure Container Registry
              run: az acr login --name ${{ steps.getacrname.outputs.acrName }}

            - name: Purge old images from ACR            
              run: |
                ACR_NAME=${{ steps.getacrname.outputs.acrName }}
                REPOS=$(az acr repository list --name $ACR_NAME --output tsv)
                
                for REPO in $REPOS; do
                    echo "Checking repository: $REPO"
                    ALL_TAGS=$(az acr repository show-tags --name $ACR_NAME --repository $REPO --orderby time_asc --output tsv)
                    
                    IMAGE_COUNT=$(echo "$ALL_TAGS" | wc -l)
                    
                    if [[ $IMAGE_COUNT -le 3 ]]; then
                        echo "Skipping cleanup for $REPO (only $IMAGE_COUNT images found)"
                        continue
                    fi
                    
                    KEEP_TAGS=$(echo "$ALL_TAGS" | head -n 3)
                    
                    for TAG in $ALL_TAGS; do
                        if [[ ! " ${KEEP_TAGS[@]} " =~ " ${TAG} " ]]; then
                            echo "Deleting old image: $REPO:$TAG"
                            az acr repository delete --name $ACR_NAME --image "$REPO:$TAG" --yes
                        fi
                    done
                done
